#!/bin/sh

set -euo pipefail

BASEDIR=$(realpath $(dirname "$0"))

static_dir="$BASEDIR/static_files"
static_out_dir="$BASEDIR/libs/static_files"

static_out_c="$static_out_dir/static_files.c"
static_out_header="$static_out_dir/include/static_files.h"

static_out_hex_dir="$static_out_dir/hex"

autogenerate_header="
// ---------------------------------------
// THIS FILE IS AUTOGENERATED; DO NOT EDIT
// ---------------------------------------

#include \"str.h\"
";

mkdir --parents $(dirname $static_out_header)
echo -e "#pragma once\n$autogenerate_header" > $static_out_header
echo "$autogenerate_header" > $static_out_c

pushd $static_dir

for file in $(find . -type f -printf '%P\n'); do
    variable_name=$(echo "static_file_$file" | sed -e s/\\./_/g -e s/\\//__/g -)
    in_file="$file" 
    out_file_hex=$(realpath -m "$static_out_hex_dir/$file.hex")

    mkdir --parents $(dirname $out_file_hex)
    
    xxd -p "$in_file" "$out_file_hex"
    echo "const static uint8_t ${variable_name}_buf[] = {" >> $static_out_c
    sed -r "s/(.{2})/0x\\1\\,/g" "$out_file_hex" >> $static_out_c
    echo "};
const str_t ${variable_name} = {
    .ptr = ${variable_name}_buf,
    .len = sizeof(${variable_name}_buf),
};" >> $static_out_c

    echo "extern const str_t ${variable_name};" >> $static_out_header
done

popd
